'use client';

/**
 * "Here is what you just made."
 *
 * Appears once a build finishes, in the results view, above everything else. A
 * pack of twenty documents across six folders is obvious to whoever built it
 * and opaque to whoever receives it; this is the picture that closes that gap
 * before anyone opens the archive.
 *
 * The SVG is generated by the same function the export uses, so the picture
 * here and the picture in the zip are the same file.
 */
import * as React from 'react';
import { FolderTree } from 'lucide-react';
import {
  buildStructure,
  buildStructureSvg,
  type StructureDoc,
} from '@/lib/structure-map';
import { slugify } from '@/lib/slots';
import type { DocumentSummary, ComparisonSummary } from '@/lib/types';
import { Eyebrow } from '@/components/ui/primitives';

export function StructureCard({
  documents,
  comparisons,
  companyName,
  formats = ['PDF', 'Excel'],
}: {
  documents: DocumentSummary[];
  comparisons: ComparisonSummary[];
  companyName: string | null;
  formats?: string[];
}) {
  const svg = React.useMemo(() => {
    const usable = documents.filter(
      (doc) => doc.status === 'complete' || doc.status === 'repaired' || doc.status === 'failed',
    );
    if (!usable.length) return null;

    const docs: StructureDoc[] = usable.map((doc) => ({
      serviceIndex: doc.serviceIndex,
      serviceName: doc.serviceName,
      tier: doc.tier === 'focused' ? 'focused' : 'generic',
      serviceSlug: doc.serviceSlug,
      awarenessLabel: doc.awarenessLabel,
    }));

    const stamp = new Date().toISOString().slice(0, 10).replace(/-/g, '');
    return buildStructureSvg(
      buildStructure({
        zipName: `${slugify(companyName || 'icp')}-icp-pack-${stamp}.zip`,
        companyName,
        documents: docs,
        comparisonFor: comparisons.map((c) => c.serviceIndex),
        formats,
      }),
    );
  }, [documents, comparisons, companyName, formats]);

  if (!svg) return null;

  return (
    <section className="rounded-xl border border-line bg-surface-1 p-4 shadow-e1 sm:p-5">
      <div className="mb-3 flex items-center gap-2">
        <FolderTree className="size-3.5 text-accent" />
        <Eyebrow>What your download contains</Eyebrow>
      </div>

      <div
        className="overflow-x-auto rounded-lg border border-line bg-white"
        // Our own generated markup, escaped at the source. Nothing here comes
        // from the model — only names the user typed, which buildStructureSvg
        // escapes before they reach the document.
        dangerouslySetInnerHTML={{ __html: svg }}
      />

      <p className="mt-3 text-xs leading-relaxed text-pretty text-fg-muted">
        This same picture is saved inside the download as{' '}
        <code className="mono text-2xs">folder-structure.svg</code>, alongside{' '}
        <code className="mono text-2xs">FILE-STRUCTURE.txt</code> which says the same thing in
        plain words.
      </p>
    </section>
  );
}
